.TH "cdpfglrestore" "1" "" "cdpfglrestore user manual" "version 0.0.9"
.SH NAME
.PP
\f[B]cdpfglrestore\f[] \- restores already saved files from a
cdpfglserver to your local filesystem.
.SH SYNOPSIS
.PP
\f[B]cdpfglrestore\f[] [options]
.SH DESCRIPTION
.PP
cdpfglrestore will restore already saved files from a cdpfglserver to
your local filesystem.
.SH COMMAND\-LINE OPTIONS
.PP
\-h, \-\-help Gives some basic help about program invocation and its
options.
.PD 0
.P
.PD
\-d, \-\-debug=0|1 When invoked with 0 debug mode is turned off.
Debug mode is turned on when invoked with 1.
When on this mode is really verbose and may slow down the program.
You should not use this option in daily normal use.
.PD 0
.P
.PD
\-v, \-\-version Gives compiled version of cdpfglrestore plus some
informations about libraries that were compiled with it and also some
configuration informations as the program has loaded them.
.PD 0
.P
.PD
\-c, \-\-configuration=FILENAME Specify an alternative configuration
file.
This file is read instead of the default one.
.SH SEE ALSO
.PP
\f[B]cdpfglclient\f[](1), \f[B]cdpfglserver\f[](1)
.SH FILES
.PP
/etc/cdpfgl/restore.conf
.SH BUGS
.PP
Please report bugs by either filling a pull request at
(http://example.com/ <https://github.com/dupgit/sauvegarde/pulls> or by
sending a mail to Olivier Delhomme <olivier.delhomme@free.fr>
.SH AUTHORS
.PP
Authors in alphabetical order are :
.IP \[bu] 2
Pierre Bourgin <pierre.bourgin@free.fr>
.PD 0
.P
.PD
.IP \[bu] 2
Olivier Delhomme <olivier.delhomme@free.fr>
.PD 0
.P
.PD
.IP \[bu] 2
Sebastien Tricaud <sebastien@honeynet.org>
