.TH "cdpfglclient" "1" "" "cdpfglclient user manual" "version 0.0.9"
.SH NAME
.PP
\f[B]cdpfglclient\f[] \- saves your files to a cdpfglserver while being
modified or created
.SH SYNOPSIS
.PP
\f[B]cdpfglclient\f[] [options]
.SH DESCRIPTION
.PP
cdpfglclient will monitor the filesystem for file creation or changes
and will save them to a cdpfglserver that might be up and working.
.SH COMMAND\-LINE OPTIONS
.PP
\-h, \-\-help Gives some basic help about program invocation and its
options.
.PD 0
.P
.PD
\-v, \-\-version Gives compiled version of cdpfgclient plus some
informations about libraries that were compiled with it and also some
configuration informations as the program has loaded them.
.PD 0
.P
.PD
\-c, \-\-configuration=FILENAME Specify an alternative configuration
file.
This file is read instead of the default one.
.SH SEE ALSO
.PP
\f[B]cdpfglrestore\f[](1), \f[B]cdpfglserver\f[](1)
.SH FILES
.PP
/etc/cdpfgl/client.conf Default configuration file.
.SH BUGS
.PP
Please report bugs by either filling a pull request at
(http://example.com/ <https://github.com/dupgit/sauvegarde/pulls> or by
sending a mail to Olivier Delhomme <olivier.delhomme@free.fr>
.SH AUTHORS
.PP
Authors in alphabetical order are :
.IP \[bu] 2
Pierre Bourgin <pierre.bourgin@free.fr>
.PD 0
.P
.PD
.IP \[bu] 2
Olivier Delhomme <olivier.delhomme@free.fr>
.PD 0
.P
.PD
.IP \[bu] 2
Sebastien Tricaud <sebastien@honeynet.org>
