.TH "cdpfglrestore" "1" "" "cdpfglrestore user manual" "version 0.0.9"
.SH NAME
.PP
\f[B]cdpfglrestore\f[] \- restores already saved files from a
cdpfglserver to your local filesystem.
.SH SYNOPSIS
.PP
\f[B]cdpfglrestore\f[] [options]
.SH DESCRIPTION
.PP
cdpfglrestore will restore already saved files from a cdpfglserver to
your local filesystem.
.SH SEE ALSO
.PP
\f[B]cdpfglclient\f[](1), \f[B]cdpfglserver\f[](1)
.SH COMMAND\-LINE OPTIONS
.SH FILES
.PP
/etc/cdpfgl/restore.conf
.SH BUGS
.PP
Please report bugs by either filling a pull request at
(http://example.com/ <https://github.com/dupgit/sauvegarde/pulls> or by
sending a mail to Olivier Delhomme <olivier.delhomme@free.fr>
.SH AUTHORS
.PP
Authors in alphabetical order are :
.IP \[bu] 2
Pierre Bourgin <pierre.bourgin@free.fr>
.IP \[bu] 2
Olivier Delhomme <olivier.delhomme@free.fr>
.IP \[bu] 2
Sebastien Tricaud <sebastien@honeynet.org>
